In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("housing.csv")

In [3]:
df.head(5)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [4]:
df['mainroad'].value_counts()

yes    468
no      77
Name: mainroad, dtype: int64

In [5]:
df['furnishingstatus'].value_counts()

semi-furnished    227
unfurnished       178
furnished         140
Name: furnishingstatus, dtype: int64

In [6]:
df.shape

(545, 13)

### One-Hot Encoding:
###      It is used to convert Categoriacal data into vectors.

In [7]:
# one hot encoding using pandas
df_dummy = pd.get_dummies(df ,columns = ['mainroad','guestroom','basement','airconditioning','furnishingstatus'])
df_dummy

,price,area,bedrooms,bathrooms,stories,hotwaterheating,parking,prefarea,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,basement_no,basement_yes,airconditioning_no,airconditioning_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,no,2,yes,0,1,1,0,1,0,0,1,1,0,0
1,12250000,8960,4,4,4,no,3,no,0,1,1,0,1,0,0,1,1,0,0
2,12250000,9960,3,2,2,no,2,yes,0,1,1,0,0,1,1,0,0,1,0
3,12215000,7500,4,2,2,no,3,yes,0,1,1,0,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,no,2,no,0,1,0,1,0,1,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,no,2,no,0,1,1,0,0,1,1,0,0,0,1
541,1767150,2400,3,1,1,no,0,no,1,0,1,0,1,0,1,0,0,1,0
542,1750000,3620,2,1,1,no,0,no,0,1,1,0,1,0,1,0,0,0,1
543,1750000,2910,3,1,1,no,0,no,1,0,1,0,1,0,1,0,1,0,0
544,1750000,3850,3,1,2,no,0,no,0,1,1,0,1,0,1,0,0,0,1

In [8]:
#K-1 One hot encoding
pd.get_dummies(df ,columns = ['mainroad','guestroom','basement','airconditioning','furnishingstatus'],drop_first = True)

,price,area,bedrooms,bathrooms,stories,hotwaterheating,parking,prefarea,mainroad_yes,guestroom_yes,basement_yes,airconditioning_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,no,2,yes,1,0,0,1,0,0
1,12250000,8960,4,4,4,no,3,no,1,0,0,1,0,0
2,12250000,9960,3,2,2,no,2,yes,1,0,1,0,1,0
3,12215000,7500,4,2,2,no,3,yes,1,0,1,1,0,0
4,11410000,7420,4,1,2,no,2,no,1,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,no,2,no,1,0,1,0,0,1
541,1767150,2400,3,1,1,no,0,no,0,0,0,0,1,0
542,1750000,3620,2,1,1,no,0,no,1,0,0,0,0,1
543,1750000,2910,3,1,1,no,0,no,0,0,0,0,0,0
544,1750000,3850,3,1,2,no,0,no,1,0,0,0,0,1

In [9]:
df.head(5)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [10]:
x = df.drop('price' , axis =1)
y = df['price']

In [11]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(x ,y ,test_size = 0.2 , random_state = 42)

In [12]:
X_train.head(5)

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
46,6000,3,2,4,yes,no,no,no,yes,1,no,furnished
93,7200,3,2,1,yes,no,yes,no,yes,3,no,semi-furnished
335,3816,2,1,1,yes,no,yes,no,yes,2,no,furnished
412,2610,3,1,2,yes,no,yes,no,no,0,yes,unfurnished
471,3750,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [13]:
X_test.head()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
316,5900,4,2,2,no,no,yes,no,no,1,no,unfurnished
77,6500,3,2,3,yes,no,no,no,yes,0,yes,furnished
360,4040,2,1,1,yes,no,no,no,no,0,no,semi-furnished
90,5000,3,1,2,yes,no,no,no,yes,0,no,semi-furnished
493,3960,3,1,1,yes,no,no,no,no,0,no,furnished

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
ohe = OneHotEncoder(sparse = False , drop = 'first')

In [16]:
x_train_new = ohe.fit_transform(X_train[['mainroad','guestroom','basement','airconditioning','furnishingstatus']])
x_train_new

C:\Users\vedus\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

array([[1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 1., 1., 0.],
       [1., 0., 1., 1., 0., 0.],
       ...,
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 0., 1., 1., 0.]])

In [17]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [18]:
new_df  = np.hstack((X_train[['area','bedrooms','bathrooms','parking']].values, x_train_new))

In [19]:
new_df

array([[6.000e+03, 3.000e+00, 2.000e+00, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [7.200e+03, 3.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [3.816e+03, 2.000e+00, 1.000e+00, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [4.500e+03, 3.000e+00, 2.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [4.040e+03, 2.000e+00, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [5.500e+03, 3.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        0.000e+00]])

In [20]:
from sklearn.compose import ColumnTransformer

In [21]:
cate_cols = x.select_dtypes(include = 'object').columns.tolist()

In [22]:
preprocessor = ColumnTransformer(transformers = [('cat' , OneHotEncoder(drop = 'first') , cate_cols)]
                                 , remainder = 'passthrough')

In [23]:
preprocessor.fit_transform(X_train).shape

(436, 13)

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

In [25]:
pipeline = Pipeline(steps = [
    ('preprocessor' , preprocessor),
    ('regresssor' , LinearRegression()) 
])

In [26]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(x ,y ,test_size = 0.2 , random_state = 42)

In [ ]:
X_train = pre

In [27]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['mainroad', 'guestroom',
                                                   'basement',
                                                   'hotwaterheating',
                                                   'airconditioning',
                                                   'prefarea',
                                                   'furnishingstatus'])])),
                ('regresssor', LinearRegression())])

In [28]:
x_train_score = pipeline.score(X_train , y_train)

In [29]:
X_test_score = pipeline.score(X_test , y_test)

In [30]:
x_train_score

0.6859438988560158

In [31]:
X_test_score

0.6529242642153155

In [32]:
X_train

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
46,6000,3,2,4,yes,no,no,no,yes,1,no,furnished
93,7200,3,2,1,yes,no,yes,no,yes,3,no,semi-furnished
335,3816,2,1,1,yes,no,yes,no,yes,2,no,furnished
412,2610,3,1,2,yes,no,yes,no,no,0,yes,unfurnished
471,3750,3,1,2,yes,no,no,no,no,0,no,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...
71,6000,4,2,4,yes,no,no,no,yes,0,no,unfurnished
106,5450,4,2,1,yes,no,yes,no,yes,0,yes,semi-furnished
270,4500,3,2,3,yes,no,no,yes,no,1,no,furnished
435,4040,2,1,1,yes,no,no,no,no,0,no,unfurnished
102,5500,3,2,4,yes,yes,no,no,yes,1,no,semi-furnished